### PR TITLE
support more node versions

### PR DESCRIPTION
**Pull request by joeferner**

### CODE REVIEW

**Comment by Apollon77** [comment]
@joeferner is there any chance to continue with this and add more versions?

**Comment by joeferner** [comment]
I don't really have time to work on this but this is a starting place if someone happens to want to take it on

**Comment by Apollon77** [comment]
I will have a look .. in fact one reason I already know ... Nodejs 18+ changed the default dns resolution orer to ipv6-first ... thats why the "localhost" fallsback when no host is given will run into issues in testing ... but there's more ... lets see

**Comment by Apollon77** [comment]
hehe ... no thats basically it ... will do a PR

**Pull request closed without merging**
