### PR TITLE
Convert ES5 code to ES2020, add typescript definitions and exports, bump package versions

### PR DESCRIPTION
**Pull request by jonluca**
* Converted the package from the old var/`Object.prototype`/require syntax into the newer ES2020 syntax
* Added typescript outputs
* Converted and fixed some tests and outputs

I know this is a large PR with some breaking changes, so I'm happy to republish this as it's own fork, but figured this would be a nice update to the overall package.

### CODE REVIEW

**Comment by joeferner** [comment]
can you ignore the `dist` directory in `.gitignore` please. Otherwise it looks really good thank you.

**Comment by jonluca** [comment]
Done. I'm also not 100% sure if the `bin` works properly now, at least when run via `npx`. Import based code should still work, although it would be useful to verify with some projects that you are familiar with.

**Review by joeferner — APPROVED** [review]

**Comment by joeferner** [comment]
Looks like some test failures... I just updated master and got rid of the older unsupported node versions. Would you mind merging the latest master into this branch to get the unit tests working.

**Comment by jonluca** [comment]
Also question on this line of code - https://github.com/joeferner/node-http-mitm-proxy/pull/259

Should this be 

```
hosts.forEach((host) => {
  self.sslServers[host] = sslServer;
});
```

Not too familiar with this specific section but thought it looked funny

**Pull request merged**
