### PR TITLE
Close callback

### PR DESCRIPTION
**Pull request by bjowes**
To allow a graceful shutdown, it is quite convenient to get a callback when proxy.close has managed to close all connections. Since the function is async there is currently no way to determine when close has actually completed. With this callback this is now possible.

The PR also fixes the issue that multiple calls to proxy.close threw errors.

Added a devDependency on keepalive-proxy-agent, since the request package couldn't handle keep-alive when proxying to https sites (through a tunnel). This was required for proper unit testing.

General: Improved unit tests of keep-alive scenarios, I found that the keep-alive option of the proxy itself wasn't used in the unit tests.

### CODE REVIEW

**Comment by bjowes** [comment]
I see the tests need a bit more work for compatibility with node 7. Will reopen when that is done.

**Comment by Apollon77** [comment]
@bjowes any plans to "re-do" the PR? else I would try ...

**Comment by bjowes** [comment]
@Apollon77 - you are more than welcome to continue working on this. I found that for my use case, I could resolve this by other means (making sure to close all connections).

**Comment by Apollon77** [comment]
kk, will get on it later if noone else is faster

**Pull request closed without merging**
